# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@chevrotain/cst-dts-gen-11.0.3" = {
      name = "_at_chevrotain_slash_cst-dts-gen";
      packageName = "@chevrotain/cst-dts-gen";
      version = "11.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@chevrotain/cst-dts-gen/-/cst-dts-gen-11.0.3.tgz";
        sha512 = "BvIKpRLeS/8UbfxXxgC33xOumsacaeCKAjAeLyOn7Pcp95HiRbrpl14S+9vaZLolnbssPIUuiUd8IvgkRyt6NQ==";
      };
    };
    "@chevrotain/gast-11.0.3" = {
      name = "_at_chevrotain_slash_gast";
      packageName = "@chevrotain/gast";
      version = "11.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@chevrotain/gast/-/gast-11.0.3.tgz";
        sha512 = "+qNfcoNk70PyS/uxmj3li5NiECO+2YKZZQMbmjTqRI3Qchu8Hig/Q9vgkHpI3alNjr7M+a2St5pw5w5F6NL5/Q==";
      };
    };
    "@chevrotain/regexp-to-ast-11.0.3" = {
      name = "_at_chevrotain_slash_regexp-to-ast";
      packageName = "@chevrotain/regexp-to-ast";
      version = "11.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@chevrotain/regexp-to-ast/-/regexp-to-ast-11.0.3.tgz";
        sha512 = "1fMHaBZxLFvWI067AVbGJav1eRY7N8DDvYCTwGBiE/ytKBgP8azTdgyrKyWZ9Mfh09eHWb5PgTSO8wi7U824RA==";
      };
    };
    "@chevrotain/types-11.0.3" = {
      name = "_at_chevrotain_slash_types";
      packageName = "@chevrotain/types";
      version = "11.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@chevrotain/types/-/types-11.0.3.tgz";
        sha512 = "gsiM3G8b58kZC2HaWR50gu6Y1440cHiJ+i3JUvcp/35JchYejb2+5MVeJK0iKThYpAa/P2PYFV4hoi44HD+aHQ==";
      };
    };
    "@chevrotain/utils-11.0.3" = {
      name = "_at_chevrotain_slash_utils";
      packageName = "@chevrotain/utils";
      version = "11.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@chevrotain/utils/-/utils-11.0.3.tgz";
        sha512 = "YslZMgtJUyuMbZ+aKvfF3x1f5liK4mWNxghFRv7jqRR9C3R3fAOGTTKvxXDa2Y1s9zSbcpuO0cAxDYsc9SrXoQ==";
      };
    };
    "chevrotain-11.0.3" = {
      name = "chevrotain";
      packageName = "chevrotain";
      version = "11.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chevrotain/-/chevrotain-11.0.3.tgz";
        sha512 = "ci2iJH6LeIkvP9eJW6gpueU8cnZhv85ELY8w8WiFtNjMHA5ad6pQLaJo9mEly/9qUyCpvqX8/POVUTf18/HFdw==";
      };
    };
    "chevrotain-allstar-0.3.1" = {
      name = "chevrotain-allstar";
      packageName = "chevrotain-allstar";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/chevrotain-allstar/-/chevrotain-allstar-0.3.1.tgz";
        sha512 = "b7g+y9A0v4mxCW1qUhf3BSVPg+/NvGErk/dOkrDaHA0nQIQGAtrOjlX//9OQtRlSCy+x9rfB5N8yC71lH1nvMw==";
      };
    };
    "lodash-4.17.21" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz";
        sha512 = "v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
      };
    };
    "lodash-es-4.17.21" = {
      name = "lodash-es";
      packageName = "lodash-es";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash-es/-/lodash-es-4.17.21.tgz";
        sha512 = "mKnC+QJ9pWVzv+C4/U3rRsHapFfHvQFoFB92e52xeyGMcX6/OlIl78je1u8vePzYZSkkogMPJ2yjxxsb89cxyw==";
      };
    };
  };
  args = {
    name = "java-parser";
    packageName = "java-parser";
    version = "2.3.0";
    src = ./.;
    dependencies = [
      sources."@chevrotain/cst-dts-gen-11.0.3"
      sources."@chevrotain/gast-11.0.3"
      sources."@chevrotain/regexp-to-ast-11.0.3"
      sources."@chevrotain/types-11.0.3"
      sources."@chevrotain/utils-11.0.3"
      sources."chevrotain-11.0.3"
      sources."chevrotain-allstar-0.3.1"
      sources."lodash-4.17.21"
      sources."lodash-es-4.17.21"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Java Parser in JavaScript";
      license = "Apache-2.0";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
